/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
const viewData = {
    id: "Employees-vue",
    label: "Employees-vue",
    factory: "frame",
    region: "center",
    link: "/services/web/codbex-edm-vue-element-plus/vue/Employees/index.html",
    perspectiveName: "entities",
};

if (typeof exports !== 'undefined') {
    exports.getView = function () {
        return viewData;
    }
}
